#!/usr/bin/env bash
set -euo pipefail

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
SCRIPT="$ROOT/scripts/run-podman-devtool.sh"

test -x "$SCRIPT"
bash -n "$SCRIPT"
grep -Fq 'podman info' "$SCRIPT"
grep -Fq 'assert-canonical-repository.sh' "$SCRIPT"
grep -Fq ':/workspace/project:rw' "$SCRIPT"
grep -Fq ':/workspace/agl:ro' "$SCRIPT"
grep -Fq 'FLUORITE_MAC_DEVTOOL_STATE_ROOT' "$SCRIPT"
grep -Fq 'TMPDIR="$container_tmp"' "$SCRIPT"
grep -Fq 'state paths must share one host filesystem' "$SCRIPT"
grep -Fq 'state_device=$(stat -f '\''%d'\'' "$state_root/build")' "$SCRIPT"
grep -Fq 'container_tmp=/workspace/tmp' "$SCRIPT"
grep -Fq 'mkdir -p "$TMPDIR/work"' "$SCRIPT"
grep -Fq 'chown "$DEVTOOL_UID:$DEVTOOL_GID" "$TMPDIR/work"' "$SCRIPT"
grep -Fq 'bitbake_control=/tmp/fluorite-bitbake-control' "$SCRIPT"
grep -Fq 'FLUORITE_MAC_BITBAKE_RESPONSE_TIMEOUT_SECONDS' "$SCRIPT"
grep -Fq 'bitbake-client-timeout/sitecustomize.py' "$SCRIPT"
grep -Fq 'FLUORITE_BITBAKE_CLIENT_RESPONSE_TIMEOUT' "$SCRIPT"
grep -Fq 'FLUORITE_MAC_DEVTOOL_RECIPE_PROFILE' "$SCRIPT"
grep -Fq 'fluorite-bitbake-focused-control' "$SCRIPT"
grep -Fq 'focused_no_extract=1' "$SCRIPT"
grep -Fq 'FOCUSED_NO_EXTRACT' "$SCRIPT"
grep -Fq 'operation" = finish-source' "$SCRIPT"
grep -Fq 'BBFILES += \\\"/workspace/project/layers/meta-fluorite-trial/recipes-graphics/flutter-apps/%s_git.bb' "$SCRIPT"
grep -Fq 'TMPDIR = \\\"/workspace/tmp\\\"' "$SCRIPT"
grep -Fq 'devtool finish --no-clean' "$SCRIPT"
grep -Fq 'DEVTOOL_FINISH_NO_CLEAN' "$SCRIPT"
grep -Fq 'BITBAKE_CONTROL_DIR' "$SCRIPT"
grep -Fq 'workspace_path = %s' "$SCRIPT"
grep -Fq 'workspace_layer_template=' "$SCRIPT"
grep -Fq 'WORKSPACE_LAYER_TEMPLATE=' "$SCRIPT"
grep -Fq 'workspace_conf/layer.conf' "$SCRIPT"
grep -Fq 'source "$BITBAKE_ENV_SCRIPT" "$BUILDDIR"' "$SCRIPT"
grep -Fq 'recipe-task' "$SCRIPT"
grep -Fq 'source-git-repair' "$SCRIPT"
grep -Fq 'filament-vk-source-head.bundle' "$SCRIPT"
grep -Fq 'prune-stale-filament-workspace' "$SCRIPT"
grep -Fq 'stale attic hash mismatch' "$SCRIPT"
grep -Fq 'stale Filament append hash mismatch' "$SCRIPT"
grep -Fq 'source-git-stash' "$SCRIPT"
grep -Fq 'source-git-stash-pop' "$SCRIPT"
grep -Fq 'source Git stash object was not removed after pop' "$SCRIPT"
grep -Fq 'source-git-commit-baseline' "$SCRIPT"
grep -Fq 'source-git-revision' "$SCRIPT"
grep -Fq 'source-git-commit-all' "$SCRIPT"
grep -Fq 'source-git-repoint-branch' "$SCRIPT"
grep -Fq 'git -C "$source_tree" -c submodule.recurse=false add -u --' "$SCRIPT"
grep -Fq 'ls-files --others --exclude-standard' "$SCRIPT"
grep -Fq 'git -C "$source_tree" read-tree --empty' "$SCRIPT"
grep -Fq 'generated_count=$generated_count' "$SCRIPT"
grep -Fq '/bin/bash -s -- "$source_tree" "$source_path" "$commit_message"' "$SCRIPT"
grep -Fq 'source Git add . staged an unexpected path' "$SCRIPT"
grep -Fq 'fluorite-old-patched-baseline' "$SCRIPT"
grep -Fq 'only do_patch and do_configure are allowed in the Mac recipe gate' "$SCRIPT"
grep -Fq 'exec bitbake -c "$TASK" -f "$RECIPE"' "$SCRIPT"
grep -Fq 'Mac recipe task gate requires TMPDIR xattr support' "$SCRIPT"
grep -Fq 'test "$1" = --no-extract' "$SCRIPT"
grep -Fq '/workspace/state/build/workspace/sources/*|/workspace/state/build/workspace/attic/sources/*' "$SCRIPT"
grep -Fq '/workspace/state/build/*|/workspace/project/*' "$SCRIPT"
grep -Fq '/workspace/state/build/*|/workspace/project/*' "$ROOT/tools/yocto-devtool/run-devtool.sh"
grep -Fq '/workspace/project/tools/yocto-devtool/run-devtool.sh' "$SCRIPT"
grep -Fq 'modify requires a recipe or --no-extract recipe source tree' "$ROOT/tools/yocto-devtool/run-devtool.sh"
grep -Fq 'test "$1" = --no-extract' "$ROOT/tools/yocto-devtool/run-devtool.sh"
grep -Fq -- '--security-opt label=disable' "$SCRIPT"
grep -Fq 'find "$state_dir" -ignore_readdir_race -xdev \( -type d -o -type f \)' "$SCRIPT"
grep -Fq 'test -e "$path" || continue' "$SCRIPT"
grep -Fq 'chown "$uid:$gid" "$path"' "$SCRIPT"
grep -Fq 'chmod u+x "$native_bin/$tool"' "$SCRIPT"
grep -Fq 'recipe-sysroot-native/usr/bin' "$SCRIPT"
grep -Fq 'mkfifo' "$SCRIPT"
grep -Fq 'cp -afl --preserve=xattr' "$SCRIPT"
grep -Fq 'tmpdir=state-bind-ownership-fifo-xattr=PASS' "$SCRIPT"
! grep -Fq '/workspace/state/tmp' "$SCRIPT"
grep -Fq -- '--tmpfs "$container_tmp:rw,size=3g"' "$SCRIPT"
! grep -Fq 'podman exec --privileged' "$SCRIPT"
grep -Fq 'EXTRA_BBLAYERS=/workspace/project/layers/meta-fluorite-trial /workspace/agl/meta-vulkan' "$SCRIPT"
! grep -Fq '/workspace/agl/self-install/meta-flutter' "$SCRIPT"
! grep -Fq '/workspace/agl/self-install/meta-flutter/meta-flutter-apps' "$SCRIPT"
grep -Fq 'backend/socket unavailable' "$SCRIPT"
grep -Fq 'status=PASS project=rw agl=ro state-bind=rw' "$SCRIPT"
grep -Fq 'repair=deferred' "$SCRIPT"
grep -Fq '/workspace/state/build/workspace/finish-layer' "$SCRIPT"
grep -Fq 'fixed finish layer template is missing' "$SCRIPT"
grep -Fq 'tools/yocto-devtool/finish-layer' "$SCRIPT"
grep -Fq 'tools/yocto-devtool/workspace-layer/conf/layer.conf' "$SCRIPT"
grep -Fq 'if test "$operation" = status' "$SCRIPT"
grep -Fq 'devtool-status' "$SCRIPT"
grep -Fq 'exec devtool status' "$ROOT/tools/yocto-devtool/run-devtool.sh"
! grep -Eq 'podman (machine )?(init|rm|system reset)|podman volume rm|podman rm' "$SCRIPT"
grep -Fq 'historical self-install checkout' "$ROOT/tools/yocto-devtool/entrypoint.sh"
grep -Fq '/workspace/agl/self-install/meta-flutter' "$ROOT/tools/yocto-devtool/entrypoint.sh"

echo 'PASS: Podman Devtool mount and reuse contract'
