# Fixed non-project destination used only for official devtool finish output.
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "fluorite-devtool-finish"
BBFILE_PATTERN_fluorite-devtool-finish = "^${LAYERDIR}/"
BBFILE_PRIORITY_fluorite-devtool-finish = "1"
LAYERSERIES_COMPAT_fluorite-devtool-finish = "scarthgap"
